from argparse import ArgumentParser
def create_parser():
    parser = ArgumentParser()
    parser.add_argument('--hidden_size', help='hidden_size', type=int, default = 450)
    parser.add_argument('--batch_size', help='batch_size', type=int, default=32)
    parser.add_argument('--num_layer', help='num_layer',type=int, default = 1)
    parser.add_argument('--checkpoint_path', help='checkpoint_path',default="checkpoint")
    parser.add_argument('--save_path', help='save_path', default='checkpoint/')
    parser.add_argument('--data_dir', default='/home/ywzhang/xsy/data/snli_1.0')
    parser.add_argument("--train_data",default="train_data.pkl")
    parser.add_argument("--valid_data",default="dev_data.pkl")
    parser.add_argument("--test_data", default="test_data.pkl")
    parser.add_argument("--dropout",default=0.4)
    parser.add_argument("--num_classes",default=3)
    parser.add_argument("--epochs",default=100)
    parser.add_argument("--lr",default=0.0004)
    parser.add_argument("--patience",default=3)
    parser.add_argument("--max_gradient_norm",default=10.0)
    parser.add_argument("--local_rank",type = int,default=-1)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--multimodel", action="store_true")
    parser.add_argument("--pooling_method", default="max_avg_max_avg")
    parser.add_argument("--model", type=str, default="bert")
    parser.add_argument("--model_size", type=str, default="base")
    parser.add_argument("--fine_tune", default=False, action="store_true")
    parser = parser.parse_args()
    return parser
